CREATE table T_youxinpai
(
    C_ID                  int primary key IDENTITY (1,1),
    C_wareHouseTime       nvarchar(200),
    C_auctionStatus       nvarchar(200),
    C_auctionTitle        nvarchar(200),
    C_auctionType         nvarchar(200),
    C_bidEndTime          nvarchar(200),
    C_bidStartTime        nvarchar(200),
    C_carCityName         nvarchar(200),
    C_carColor            nvarchar(200),
    C_carPlaceCity        nvarchar(200),
    C_channelCount        nvarchar(200),
    C_channelTitle        nvarchar(200),
    C_cityId              nvarchar(200),
    C_conditionGradeSmall nvarchar(200),
    C_currentIndex        nvarchar(200),
    C_currentPublishOrder nvarchar(200),
    C_energyType          nvarchar(200),
    C_hasVideo            nvarchar(200),
    C_sourceId            nvarchar(200),
    C_imgUrl              nvarchar(200),
    C_isAttention         nvarchar(200),
    C_isNewPublish        nvarchar(200),
    C_kilometers          nvarchar(200),
    C_labelColor          nvarchar(200),
    C_labelName           nvarchar(200),
    C_mileage             nvarchar(200),
    C_parkingNum          nvarchar(200),
    C_power               nvarchar(200),
    C_pricesStart         nvarchar(200),
    C_publishType         nvarchar(200),
    C_redCar              nvarchar(200),
    C_reportViewType      nvarchar(200),
    C_reservePrice        nvarchar(200),
    C_standardCode        nvarchar(200),
    C_startPriceType      nvarchar(200),
    C_totalGrade          nvarchar(200),
    C_year                nvarchar(200),
    C_crykey              nvarchar(200)
)